spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블 만들어주는 설정
    properties:
      hibernate:
#        show_sql: true # system.out차원에서 jpa나 hibernate가 생성하는 SQL을 보여준다.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # log차원에서 jpa나 hibernate가 생성하는 SQL이 보여준다.
    org.hibernate.orm.jdbc.bind: trace